name: Daily Screener (run_pipeline)

on:
  schedule:
    - cron: "30 */8 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-screener:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: "utf-8"
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Run only at 09:30 and 17:30 Europe/Rome
        if: ${{ github.event_name == 'schedule' }}
        run: |
          NOW=$(TZ=Europe/Rome date +'%H:%M')
          echo "Europe/Rome now: $NOW"
          if [ "$NOW" != "09:30" ] && [ "$NOW" != "17:30" ]; then
            echo "Not target time — exiting without running."
            exit 0
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # web3 serve a defiFunzionante.py
            pip install requests tenacity rich web3
          fi

      - name: Run run_pipeline.py
        id: screener
        shell: bash
        run: |
          set -o pipefail
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8

          CMD="python run_pipeline.py --rpc https://bsc-dataseed.binance.org --min-liq 20000 --workers 12 --max-tickers-scan 40 --dominance 0.30 --rps-cg 0.5 --rps-ds 2.0 --funnel-show 100"
          echo "Running: $CMD"

          mkdir -p state/telegram
          OUTFILE=out.txt
          ERRFILE=err.txt

          bash -lc "$CMD" >"$OUTFILE" 2>"$ERRFILE" || true
          CODE=$?
          echo "exit_code=$CODE" >> "$GITHUB_OUTPUT"

          # Sanifica e prepara log sintetici
          SAN_OUT="out.sanitized.txt"
          SAN_ERR="err.sanitized.txt"
          tr -d '\000' < "$OUTFILE" > "$SAN_OUT" || true
          tr -d '\000' < "$ERRFILE" > "$SAN_ERR" || true

          TAIL_ERR="$(tail -n 50 "$SAN_ERR" 2>/dev/null || true)"
          {
            echo "==== run_pipeline output (truncated) ===="
            head -n 200 "$SAN_OUT" || true
            if [ -s "$SAN_ERR" ]; then
              echo ""
              echo "---- last 50 lines of STDERR ----"
              echo "$TAIL_ERR"
            fi
          } > msg.txt

      - name: Send Telegram — header
        if: env.TG_BOT_TOKEN != '' && env.TG_CHAT_ID != ''
        shell: bash
        run: |
          API="https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage"
          EXIT="${{ steps.screener.outputs.exit_code }}"
          if [ "$EXIT" = "0" ]; then
            HEADER="✅ Screener OK"
          else
            HEADER="❌ Screener ERROR ($EXIT)"
          fi
          curl -sS -X POST "$API" \
            --data-urlencode "chat_id=${TG_CHAT_ID}" \
            --data-urlencode "text=$HEADER" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=HTML" \
          || echo "Telegram send failed (header)"

      - name: Send Telegram — per-coin messages
        if: env.TG_BOT_TOKEN != '' && env.TG_CHAT_ID != ''
        shell: bash
        run: |
          API="https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage"
          shopt -s nullglob
          FILES=(state/telegram/coin_*.html)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No per-coin messages found."
            exit 0
          fi
          for f in "${FILES[@]}"; do
            TEXT="$(cat "$f")"
            curl -sS -X POST "$API" \
              --data-urlencode "chat_id=${TG_CHAT_ID}" \
              --data-urlencode "text=$TEXT" \
              -d "disable_web_page_preview=true" \
              -d "parse_mode=HTML" \
            || echo "Telegram send failed ($f)"
            sleep 0.8
          done

      - name: Send Telegram — summary (ranking)
        if: env.TG_BOT_TOKEN != '' && env.TG_CHAT_ID != ''
        shell: bash
        run: |
          API="https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage"
          if [ -f state/telegram/msg_summary.html ]; then
            TEXT="$(cat state/telegram/msg_summary.html)"
          else
            TEXT="⚠️ Nessun riepilogo generato."
          fi
          curl -sS -X POST "$API" \
            --data-urlencode "chat_id=${TG_CHAT_ID}" \
            --data-urlencode "text=$TEXT" \
            -d "disable_web_page_preview=true" \
            -d "parse_mode=HTML" \
          || echo "Telegram send failed (summary)"

      - name: Upload logs (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-pipeline-logs
          path: |
            out.txt
            err.txt
            msg.txt
            state/telegram/*.html
