name: Volume Watch (every 5m)

on:
  schedule:
    - cron: "*/5 * * * *"   # ogni 5 minuti (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: volwatch
  cancel-in-progress: true

jobs:
  volwatch:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: "utf-8"
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
      TZ: Europe/Rome

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests tenacity

      - name: Debug repo layout
        run: |
          echo "PWD:"
          pwd
          echo "Root listing:"
          ls -la
          if [ -d Trading ]; then
            echo "Trading/ listing:"
            ls -la Trading
          fi

      - name: Run Volume Watch (autodetect path + flags)
        shell: bash
        run: |
          set -euo pipefail

          # Trova lo script nella root o in Trading/
          PY="volume_watch.py"
          if [ -f "Trading/volume_watch.py" ]; then
            PY="Trading/volume_watch.py"
          elif [ ! -f "$PY" ]; then
            echo "::error::volume_watch.py non trovato né in root né in Trading/"; exit 1
          fi

          # Sanity check: volume_watch.py deve supportare --mode
          if ! grep -q -- "--mode" "$PY"; then
            echo "::error::Il file $PY NON contiene --mode (probabilmente non è la versione corretta di volume_watch.py)."
            exit 1
          fi

          python "$PY" \
            --mode from-screener \
            --min-liq 200000 \
            --workers 12 \
            --max-tickers-scan 40 \
            --dominance 0.30 \
            --rps-cg 0.5 \
            --rps-ds 2.0 \
            --funnel-show 100 \
            --skip-unchanged-days 0 \
            --send-telegram

      - name: Commit state (volwatch)
        if: always()
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Aggiungi sia i path in root che nel caso fossero in Trading/
          git add state/volwatch/*.json state/telegram/msg_volwatch.html state/top_pairs.json || true
          git add Trading/state/volwatch/*.json Trading/state/telegram/msg_volwatch.html Trading/state/top_pairs.json || true
          if ! git diff --cached --quiet; then
            git commit -m "volwatch: update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No state changes to commit."
          fi
