      - name: Send Telegram — volume watch (chunked)
        if: env.TG_BOT_TOKEN != '' && env.TG_CHAT_ID != ''
        run: |
          if [ ! -f state/telegram/msg_volwatch.html ]; then
            echo "No volume watch message generated."
            exit 0
          fi
          python scripts/tg_send_chunks.py --file state/telegram/msg_volwatch.html
